### ISSUE TITLE
课程项目题目

### ISSUE THREAD

**Issue by hduffddybz** [ECS-610/DM2410#1]
能否提供下课程项目的具体题目跟要求吗？Thank you！

**Comment by ECS-610** [comment]
@hduffddybz  已更新

**Comment by hduffddybz** [comment]
Thank you very much!没有更多的细节吗？另外实验室我用的设备不是板子烧了，就是jlink固件被更新用不了，可以用自己的板子吗（不是实验室的ARM9）？

**Comment by ECS-610** [comment]
1.还有能用的
2.这个大概不行

**Comment by hduffddybz** [comment]
能跑得起minigui的就是好同志。我还想用rtgui呢！我连硬件都没有呢，跑仿真呢！

**Comment by ECS-610** [comment]
:+1:

**Comment by ECS-610** [comment]
:+1:
